chore: derive version from package.json and enforce updates through husky and github workflow

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -19,8 +19,10 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
 
-      - name: Test code and Create Test Coverage Reports
+      - name: Setup node and install
         uses: actions/setup-node@v6
         with:
           node-version-file: .nvmrc
@@ -28,6 +30,19 @@ jobs:
       - run: |
           npm audit --omit=dev
           npm ci
+
+      - name: Verify semantic version bump
+        run: |
+          TARGET_BRANCH_VERSION=$(git show origin/${{ github.base_ref }}:package.json | jq -r '.version')
+          PR_BRANCH_VERSION=$(jq -r '.version' package.json)
+
+          if ! npx -y semver -r ">${TARGET_BRANCH_VERSION}" "${PR_BRANCH_VERSION}" > /dev/null  ; then
+            echo "ERROR: Branch package.json version (${PR_BRANCH_VERSION}) must be semantically greater than target branch (${TARGET_BRANCH_VERSION})"
+            exit 1
+          fi
+
+      - name: Test code and Create Test Coverage Reports
+        run: |
           npm run lint
           npm test
 
